name: pw-educamos-notifier
services:
  pw-educamos-notifier:
    container_name: pw-educamos-notifier
    #build: .
    image: pw-educamos-notifier:latest
    env_file:
      - .env
    restart: on-failure